using ApiGateway.Services;
using Microsoft.Extensions.Logging.Abstractions;
using Xunit;

namespace ApiGateway.Tests.Services
{
    /// <summary>
    /// Unit tests for <see cref="AuthenticatorAppService"/>.
    /// Covers both acceptance criteria:
    ///   1. Service supports generating shared secrets for new MFA setup.
    ///   2. Service can validate codes generated by authenticator apps.
    /// </summary>
    public class AuthenticatorAppServiceTests
    {
        private readonly AuthenticatorAppService _sut;

        public AuthenticatorAppServiceTests()
        {
            _sut = new AuthenticatorAppService(NullLogger<AuthenticatorAppService>.Instance);
        }

        // ── GenerateSharedSecret ─────────────────────────────────────────────────

        [Fact]
        public void GenerateSharedSecret_ReturnsNonEmptyString()
        {
            var secret = _sut.GenerateSharedSecret();
            Assert.False(string.IsNullOrWhiteSpace(secret));
        }

        [Fact]
        public void GenerateSharedSecret_ReturnsBase32EncodedString()
        {
            var secret = _sut.GenerateSharedSecret();
            // Base32 alphabet: A-Z and 2-7 (no padding required)
            Assert.Matches("^[A-Z2-7]+$", secret);
        }

        [Fact]
        public void GenerateSharedSecret_ReturnsDifferentValuesOnEachCall()
        {
            var secret1 = _sut.GenerateSharedSecret();
            var secret2 = _sut.GenerateSharedSecret();
            Assert.NotEqual(secret1, secret2);
        }

        [Fact]
        public void GenerateSharedSecret_ReturnsExpectedLength()
        {
            // 20 raw bytes → 32 Base32 characters (20 * 8 / 5 = 32)
            var secret = _sut.GenerateSharedSecret();
            Assert.Equal(32, secret.Length);
        }

        // ── ValidateCode – happy path ────────────────────────────────────────────

        [Fact]
        public void ValidateCode_WithCorrectCurrentCode_ReturnsTrue()
        {
            // Generate a secret and compute the expected TOTP for the current window
            var secret = _sut.GenerateSharedSecret();
            var code = ComputeCurrentTotp(secret);

            Assert.True(_sut.ValidateCode(secret, code));
        }

        // ── ValidateCode – rejection cases ──────────────────────────────────────

        [Fact]
        public void ValidateCode_WithWrongCode_ReturnsFalse()
        {
            var secret = _sut.GenerateSharedSecret();
            Assert.False(_sut.ValidateCode(secret, "000000"));
        }

        [Theory]
        [InlineData(null)]
        [InlineData("")]
        [InlineData("   ")]
        public void ValidateCode_WithNullOrEmptySecret_ReturnsFalse(string? secret)
        {
            Assert.False(_sut.ValidateCode(secret!, "123456"));
        }

        [Theory]
        [InlineData(null)]
        [InlineData("")]
        [InlineData("   ")]
        [InlineData("12345")]      // too short
        [InlineData("1234567")]    // too long
        [InlineData("12345a")]     // non-digit character
        public void ValidateCode_WithInvalidCodeFormat_ReturnsFalse(string? code)
        {
            var secret = _sut.GenerateSharedSecret();
            Assert.False(_sut.ValidateCode(secret, code!));
        }

        [Fact]
        public void ValidateCode_WithInvalidBase32Secret_ReturnsFalse()
        {
            // '!' is not a valid Base32 character
            Assert.False(_sut.ValidateCode("!!!INVALID!!!", "123456"));
        }

        // ── Helper: replicate TOTP computation for test assertions ───────────────

        /// <summary>
        /// Replicates the TOTP algorithm used by <see cref="AuthenticatorAppService"/>
        /// so tests can generate the expected code without exposing private members.
        /// </summary>
        private static string ComputeCurrentTotp(string base32Secret)
        {
            var secretBytes = Base32Decode(base32Secret);
            var counter = DateTimeOffset.UtcNow.ToUnixTimeSeconds() / 30;
            return ComputeHotp(secretBytes, counter);
        }

        private static string ComputeHotp(byte[] secret, long counter)
        {
            var counterBytes = BitConverter.GetBytes(counter);
            if (BitConverter.IsLittleEndian) Array.Reverse(counterBytes);

            using var hmac = new System.Security.Cryptography.HMACSHA1(secret);
            var hash = hmac.ComputeHash(counterBytes);

            int offset = hash[^1] & 0x0F;
            int truncated = ((hash[offset] & 0x7F) << 24)
                          | ((hash[offset + 1] & 0xFF) << 16)
                          | ((hash[offset + 2] & 0xFF) << 8)
                          | (hash[offset + 3] & 0xFF);

            return (truncated % 1_000_000).ToString().PadLeft(6, '0');
        }

        private static readonly char[] Base32Alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567".ToCharArray();

        private static byte[] Base32Decode(string base32)
        {
            var input = base32.ToUpperInvariant().TrimEnd('=');
            var output = new byte[input.Length * 5 / 8];
            int buffer = 0, bitsLeft = 0, index = 0;

            foreach (char c in input)
            {
                int value = Array.IndexOf(Base32Alphabet, c);
                if (value < 0) throw new FormatException($"Invalid Base32 character: '{c}'");
                buffer = (buffer << 5) | value;
                bitsLeft += 5;
                if (bitsLeft >= 8)
                {
                    bitsLeft -= 8;
                    output[index++] = (byte)((buffer >> bitsLeft) & 0xFF);
                }
            }

            return output;
        }
    }
}
