name: "Secret Scan"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  secrets_scan:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Run gitleaks to check for secrets
      uses: zricethezav/gitleaks-action@master
      with:
        args: "--path . --config .gitleaks.toml --report-format sarif"

    - name: Upload report
      uses: actions/upload-artifact@v2
      with:
        name: gitleaks-scan-report.sarif
        path: gitleaks.sarif