namespace ApiGateway.Models
{
    /// <summary>
    /// Request model for validating a TOTP code during the second-factor authentication step.
    /// Used when a user has already passed primary (username/password) authentication
    /// and must now supply the time-based one-time password from their authenticator app.
    /// </summary>
    public class MfaValidationRequest
    {
        /// <summary>
        /// The username of the user completing the second-factor challenge.
        /// </summary>
        public string Username { get; set; } = string.Empty;

        /// <summary>
        /// The 6-digit TOTP code generated by the authenticator app.
        /// </summary>
        public string TotpCode { get; set; } = string.Empty;

        /// <summary>
        /// Optional: a short-lived session token issued after primary authentication
        /// to tie the MFA challenge back to the original login attempt.
        /// </summary>
        public string? MfaSessionToken { get; set; }
    }
}
